# Generated by Django 3.1.4 on 2020-12-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='profiles',
        ),
    ]
